<?php
return [

    // all bank transection
    'bank1' => [
      "type" => "Opening Balance",
      "prefix" => "BOB",
      "bank" => "+",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "", //bank.edit
      "deleted_at" => "",
    ],
    'bank2' => [
      "type" => "Payment In",
      "prefix" => "BPI",
      "bank" => "+",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank3' => [
      "type" => "Payment Out",
      "prefix" => "BPO",
      "bank" => "-",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank4' => [
      "type" => "Cash Withdraw",
      "prefix" => "BCW",
      "bank" => "-",
      "cash" => "+",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank5' => [
      "type" => "Cash Deposit",
      "prefix" => "BCD",
      "bank" => "+",
      "cash" => "-",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank6' => [
      "type" => "Increase Balance",
      "prefix" => "BIB",
      "bank" => "+",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank7' => [
      "type" => "Reduce Balance",
      "prefix" => "BRB",
      "bank" => "-",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank8' => [
      "type" => "Bank to Bank Transfer",
      "prefix" => "BTB",
      "bank" => "-",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "bank.adjustment.delete",
    ],
    'bank9' => [
      "type" => "Cheque Deposit",
      "prefix" => "BCH",
      "bank" => "+",
      "cash" => "",
      "cheque" => "+",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'bank10' => [
      "type" => "Expenses",
      "prefix" => "BEO",
      "bank" => "-",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "edit.expenses",
      "deleted_at" => "delete.expenses.payment",
    ],
    'bank11' => [
      "type" => "Salary",
      "prefix" => "BKS",
      "bank" => "-",
      "cash" => "",
      "cheque" => "",
      "edit_at" => "karigar.salary.redirect",
      "deleted_at" => "delete.karigar.payment",
    ],
    'bank12' => [
        "type" => "Withdrawal",
        "prefix" => "BKW",
        "bank" => "-",
        "cash" => "",
        "cheque" => "",
        "edit_at" => "karigar.salary.redirect",
        "deleted_at" => "delete.karigar.payment",
    ],
    'bank13' => [
        "type" => "Process",
        "prefix" => "BKP",
        "bank" => "-",
        "cash" => "",
        "cheque" => "",
        "edit_at" => "edit.stock.process",
        "deleted_at" => "delete.process.payment",
    ],
    'bank14' => [
        "type" => "Other Income",
        "prefix" => "BOI",
        "bank" => "+",
        "cash" => "",
        "cheque" => "",
        "edit_at" => "bank.adjustment.edit",
        "deleted_at" => "bank.adjustment.delete",
    ],
    'bank15' => [
        "type" => "Invoice",
        "prefix" => "BIC",
        "bank" => "+",
        "cash" => "",
        "cheque" => "",
        "edit_at" => "edit.invoice",
        "deleted_at" => "delete.invoice.payment",
    ],
    'bank16' => [
        "type" => "Cheque Withdraw",
        "prefix" => "BCHW",
        "bank" => "+",
        "cash" => "",
        "cheque" => "+",
        "edit_at" => "",
        "deleted_at" => "",
    ],

    // all cash transection
    'cash1' => [
      "type" => "Cash Withdraw",
      "prefix" => "CCW",
      "bank" => "-",
      "cash" => "+",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash2' => [
      "type" => "Cash Deposit",
      "prefix" => "CCD",
      "bank" => "+",
      "cash" => "-",
      "cheque" => "",
      "edit_at" => "bank.adjustment.edit",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash3' => [
      "type" => "Add Cash",
      "prefix" => "CIC",
      "bank" => "",
      "cash" => "+",
      "cheque" => "",
      "edit_at" => "cash.adjustment.edit",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash4' => [
      "type" => "Reduce Cash",
      "prefix" => "CRC",
      "bank" => "",
      "cash" => "-",
      "cheque" => "",
      "edit_at" => "cash.adjustment.edit",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash5' => [
      "type" => "Payment In",
      "prefix" => "CPI",
      "bank" => "",
      "cash" => "+",
      "cheque" => "",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash6' => [
      "type" => "Payment Out",
      "prefix" => "CPO",
      "bank" => "",
      "cash" => "-",
      "cheque" => "",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "cash.adjustment.delete",
    ],
    'cash7' => [
      "type" => "Cheque Deposit",
      "prefix" => "CCH",
      "bank" => "",
      "cash" => "+",
      "cheque" => "+",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'cash8' => [
      "type" => "Expenses",
      "prefix" => "CEO",
      "bank" => "",
      "cash" => "-",
      "cheque" => "",
      "edit_at" => "edit.expenses",
      "deleted_at" => "delete.expenses.payment",
    ],
    'cash9' => [
        "type" => "Salary",
        "prefix" => "CKS",
        "bank" => "",
        "cash" => "-",
        "cheque" => "",
        "edit_at" => "karigar.salary.redirect",
        "deleted_at" => "delete.karigar.payment",
    ],
    'cash10' => [
        "type" => "Withdrawal",
        "prefix" => "CKW",
        "bank" => "",
        "cash" => "-",
        "cheque" => "",
        "edit_at" => "karigar.salary.redirect",
        "deleted_at" => "delete.karigar.payment",
    ],
    'cash11' => [
        "type" => "Process",
        "prefix" => "CKP",
        "bank" => "",
        "cash" => "-",
        "cheque" => "",
        "edit_at" => "edit.stock.process",
        "deleted_at" => "delete.process.payment",
    ],
    'cash12' => [
        "type" => "Other Income",
        "prefix" => "COI",
        "bank" => "",
        "cash" => "+",
        "cheque" => "",
        "edit_at" => "cash.adjustment.edit",
        "deleted_at" => "cash.adjustment.delete",
    ],
    'cash13' => [
        "type" => "Invoice",
        "prefix" => "CII",
        "bank" => "",
        "cash" => "+",
        "cheque" => "",
        "edit_at" => "edit.invoice",
        "deleted_at" => "delete.invoice.payment",
    ],
    'cash14' => [
        "type" => "Cheque Withdraw",
        "prefix" => "CCHW",
        "bank" => "",
        "cash" => "+",
        "cheque" => "+",
        "edit_at" => "",
        "deleted_at" => "",
    ],

    //all cheque transection
    'cheque1' => [
      "type" => "Payment In", //R
      "prefix" => "CHPI",
      "bank" => "",
      "cash" => "",
      "cheque" => "+",
      "edit_at" => "cheque.adjustment",
      "deleted_at" => "cheque.reopen",
    ],
    'cheque2' => [
      "type" => "Payment Out", //P
      "prefix" => "CHPO",
      "bank" => "",
      "cash" => "",
      "cheque" => "-",
      "edit_at" => "cheque.adjustment",
      "deleted_at" => "cheque.reopen",
    ],
    'cheque3' => [
      "type" => "Cheque Deposit", //cash
      "prefix" => "CHDC",
      "bank" => "",
      "cash" => "",
      "cheque" => "-",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'cheque4' => [
      "type" => "Cheque Deposit", //bank
      "prefix" => "CHDB",
      "bank" => "",
      "cash" => "",
      "cheque" => "-",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'cheque5' => [
      "type" => "Expenses", //p
      "prefix" => "CHEO",
      "bank" => "",
      "cash" => "",
      "cheque" => "-",
      "edit_at" => "cheque.adjustment",
      "deleted_at" => "cheque.reopen",
    ],
    'cheque6' => [
        "type" => "Salary",
        "prefix" => "CHKS",
        "bank" => "",
        "cash" => "",
        "cheque" => "-",
        "edit_at" => "cheque.adjustment",
        "deleted_at" => "cheque.reopen",
    ],
    'cheque7' => [
        "type" => "Withdrawal",
        "prefix" => "CHKW",
        "bank" => "",
        "cash" => "",
        "cheque" => "-",
        "edit_at" => "cheque.adjustment",
        "deleted_at" => "cheque.reopen",
    ],
    'cheque8' => [
        "type" => "Process",
        "prefix" => "CHKP",
        "bank" => "",
        "cash" => "",
        "cheque" => "-",
        "edit_at" => "cheque.adjustment",
        "deleted_at" => "cheque.reopen",
    ],
    'cheque9' => [
        "type" => "Invoice",
        "prefix" => "CHIC",
        "bank" => "",
        "cash" => "",
        "cheque" => "+",
        "edit_at" => "cheque.adjustment",
        "deleted_at" => "cheque.reopen",
    ],
    'cheque10' => [
        "type" => "Cheque Withdraw", //cash
        "prefix" => "CHDC",
        "bank" => "",
        "cash" => "",
        "cheque" => "-",
        "edit_at" => "",
        "deleted_at" => "",
    ],
    'cheque11' => [
        "type" => "Cheque Withdraw", //bank
        "prefix" => "CHDB",
        "bank" => "",
        "cash" => "",
        "cheque" => "-",
        "edit_at" => "",
        "deleted_at" => "",
    ],

    //payment
    'PAYIN' => [
      "type" => "Payment In",
      "prefix" => "PAYIN",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "delete.payment",
    ],
    'PAYOUT' => [
      "type" => "Payment Out",
      "prefix" => "PAYOUT",
      "edit_at" => "edit.paymentin",
      "deleted_at" => "delete.payment",
    ],
    'PAYABLE' => [
      "type" => "Payable Opening Balance",
      "prefix" => "PAYABLE",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'RECIVABLE' => [
      "type" => "Receivable Opening Balance",
      "prefix" => "RECIVABLE",
      "edit_at" => "",
      "deleted_at" => "",
    ],
    'EXPENSES' => [
      "type" => "Expenses",
      "prefix" => "EXPENSES",
      "edit_at" => "edit.expenses",
      "deleted_at" => "delete.expenses",
    ],
    'SALARY' => [
        "type" => "Salary",
        "prefix" => "SALARY",
        "edit_at" => "",
        "deleted_at" => "",
    ],
    'WITHDRAWAL' => [
        "type" => "Withdrawal",
        "prefix" => "WITHDRAWAL",
        "edit_at" => "",
        "deleted_at" => "",
    ],
    'PROCESS' => [
        "type" => "Process",
        "prefix" => "PROCESS",
        "edit_at" => "edit.stock.process",
        "deleted_at" => "delete.stock.process",
    ],
    'INVOICE' => [
        "type" => "Invoice",
        "prefix" => "INVOICE",
        "edit_at" => "edit.invoice",
        "deleted_at" => "delete.invoice",
    ],

];
